import os
from datetime import datetime
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment


# ── PDF REPORT ─────────────────────────────────────────────
def generate_skill_gap_pdf(
    matching_skills, missing_skills,
    match_percentage, summary, candidate_name="Candidate"
):
    """Generate a skill gap analysis PDF. Returns BytesIO buffer."""

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2*cm, bottomMargin=2*cm,
        leftMargin=2*cm, rightMargin=2*cm
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle', parent=styles['Heading1'],
        fontSize=22, textColor=colors.HexColor('#7c3aed'),
        spaceAfter=6
    )
    sub_style = ParagraphStyle(
        'SubStyle', parent=styles['Normal'],
        fontSize=11, textColor=colors.HexColor('#6b7280'),
        spaceAfter=20
    )
    heading_style = ParagraphStyle(
        'HeadStyle', parent=styles['Heading2'],
        fontSize=14, textColor=colors.HexColor('#1f2937'),
        spaceBefore=16, spaceAfter=10
    )
    body_style = ParagraphStyle(
        'BodyStyle', parent=styles['Normal'],
        fontSize=10.5, leading=16
    )

    elements = []

    elements.append(Paragraph("AI Career Copilot", title_style))
    elements.append(Paragraph(
        f"Skill Gap Analysis Report — {candidate_name}", sub_style
    ))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        sub_style
    ))

    # Match score box
    elements.append(Paragraph("Match Score", heading_style))
    score_table = Table(
        [[f"{match_percentage}% Match"]], colWidths=[16*cm]
    )
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#34d399')),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.white),
        ('FONTSIZE', (0,0), (-1,-1), 18),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 14),
        ('BOTTOMPADDING', (0,0), (-1,-1), 14),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 16))

    # Matching skills
    elements.append(Paragraph(
        f"Skills You Have ({len(matching_skills)})", heading_style
    ))
    matching_text = ", ".join(matching_skills) if matching_skills else "None found"
    elements.append(Paragraph(matching_text, body_style))
    elements.append(Spacer(1, 12))

    # Missing skills
    elements.append(Paragraph(
        f"Skills You Need to Learn ({len(missing_skills)})", heading_style
    ))
    missing_text = ", ".join(missing_skills) if missing_skills else "None — full match!"
    elements.append(Paragraph(missing_text, body_style))
    elements.append(Spacer(1, 12))

    # Summary
    if summary:
        elements.append(Paragraph("AI Summary", heading_style))
        elements.append(Paragraph(summary, body_style))

    elements.append(Spacer(1, 24))
    elements.append(Paragraph(
        "Generated by AI Career Copilot", sub_style
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_roadmap_pdf(weeks, goal, candidate_name="Candidate"):
    """Generate a learning roadmap PDF. Returns BytesIO buffer."""

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2*cm, bottomMargin=2*cm,
        leftMargin=2*cm, rightMargin=2*cm
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle', parent=styles['Heading1'],
        fontSize=22, textColor=colors.HexColor('#7c3aed'),
        spaceAfter=6
    )
    sub_style = ParagraphStyle(
        'SubStyle', parent=styles['Normal'],
        fontSize=11, textColor=colors.HexColor('#6b7280'),
        spaceAfter=16
    )
    week_title_style = ParagraphStyle(
        'WeekTitle', parent=styles['Heading3'],
        fontSize=13, textColor=colors.HexColor('#a78bfa'),
        spaceBefore=14, spaceAfter=6
    )
    body_style = ParagraphStyle(
        'BodyStyle', parent=styles['Normal'],
        fontSize=10, leading=15
    )

    elements = []
    elements.append(Paragraph("AI Career Copilot", title_style))
    elements.append(Paragraph(
        f"Learning Roadmap — {candidate_name}", sub_style
    ))

    if goal:
        elements.append(Paragraph(f"<b>Goal:</b> {goal}", body_style))
        elements.append(Spacer(1, 14))

    for week in weeks:
        elements.append(Paragraph(
            f"Week {week.get('number','')} — {week.get('title','')}",
            week_title_style
        ))

        if week.get('skills'):
            elements.append(Paragraph(
                f"<b>Skills:</b> {', '.join(week['skills'])}",
                body_style
            ))

        if week.get('tasks'):
            tasks_text = "<br/>".join([f"• {t}" for t in week['tasks']])
            elements.append(Paragraph(
                f"<b>Tasks:</b><br/>{tasks_text}", body_style
            ))

        if week.get('outcome'):
            elements.append(Paragraph(
                f"<b>Outcome:</b> {week['outcome']}", body_style
            ))

        elements.append(Spacer(1, 10))

    elements.append(Spacer(1, 14))
    elements.append(Paragraph(
        "Generated by AI Career Copilot", sub_style
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer


# ── EXCEL REPORT ────────────────────────────────────────────
def generate_jobs_excel(jobs, search_query="Jobs"):
    """Generate an Excel file of job search results. Returns BytesIO buffer."""

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Job Results"

    headers = [
        "Title", "Company", "Location", "Match %",
        "Salary Min", "Salary Max", "Type",
        "Posted", "Source", "Apply Link"
    ]

    header_fill = PatternFill(
        start_color="7C3AED", end_color="7C3AED", fill_type="solid"
    )
    header_font = Font(color="FFFFFF", bold=True, size=11)

    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center")

    for row_idx, job in enumerate(jobs, start=2):
        ws.cell(row=row_idx, column=1, value=job.get('title', ''))
        ws.cell(row=row_idx, column=2, value=job.get('company', ''))
        ws.cell(row=row_idx, column=3, value=job.get('location', ''))
        ws.cell(row=row_idx, column=4, value=job.get('match_score', 0))
        ws.cell(row=row_idx, column=5, value=job.get('salary_min', ''))
        ws.cell(row=row_idx, column=6, value=job.get('salary_max', ''))
        ws.cell(row=row_idx, column=7, value=job.get('job_type', ''))
        ws.cell(row=row_idx, column=8, value=job.get('posted_on', ''))
        ws.cell(row=row_idx, column=9, value=job.get('source', ''))
        ws.cell(row=row_idx, column=10, value=job.get('apply_link', ''))

    # Auto-width columns
    for col in ws.columns:
        max_len = max(
            (len(str(c.value)) for c in col if c.value), default=10
        )
        col_letter = col[0].column_letter
        ws.column_dimensions[col_letter].width = min(max_len + 4, 50)

    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer


def generate_applications_excel(applications_df):
    """Generate Excel file from job tracker applications dataframe"""

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "My Applications"

    if applications_df.empty:
        ws.cell(row=1, column=1, value="No applications yet")
        buffer = BytesIO()
        wb.save(buffer)
        buffer.seek(0)
        return buffer

    headers = list(applications_df.columns)
    header_fill = PatternFill(
        start_color="7C3AED", end_color="7C3AED", fill_type="solid"
    )
    header_font = Font(color="FFFFFF", bold=True, size=11)

    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center")

    for row_idx, row in enumerate(applications_df.itertuples(index=False), start=2):
        for col_idx, value in enumerate(row, start=1):
            ws.cell(row=row_idx, column=col_idx, value=str(value))

    for col in ws.columns:
        max_len = max(
            (len(str(c.value)) for c in col if c.value), default=10
        )
        col_letter = col[0].column_letter
        ws.column_dimensions[col_letter].width = min(max_len + 4, 50)

    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer